name: Selenium Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering of the workflow

# Limit concurrent runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Selenium Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Set a timeout to prevent hung jobs
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Build with Maven
      run: mvn clean compile
      
    - name: Run Tests
      run: mvn test
      
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports-chrome-${{ github.run_id }}
        path: |
          test-output/reports/
          test-output/screenshots/
        retention-days: 7