name: Scheduled Selenium Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  test:
    name: Run Scheduled Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Build with Maven
      run: mvn clean compile
      
    - name: Run Tests
      run: mvn test
      
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scheduled-test-reports-${{ github.run_id }}
        path: |
          test-output/reports/
          test-output/screenshots/
        retention-days: 14
        
    - name: Send email notification
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.MAIL_SERVER }}
        server_port: ${{ secrets.MAIL_PORT }}
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Scheduled Test Run Failed
        body: The scheduled test run has failed. Please check the GitHub Actions logs for more details.
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: GitHub Actions